name: Deploy application

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Enter a value for image_tag'
        required: true

permissions:
  contents: read
  id-token: write

env:
  AWS_ROLE: 'arn:aws:iam::896918338968:role/GitHubActionsMeyersAI'
  VAULT_ADDR: ${{ secrets.VAULT_ADDR }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 24

      - name: Import secret
        id: import-secret
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ env.VAULT_ADDR }}
          role: github-actions-secret
          method: jwt
          path: github-actions-secret
          secrets: |
            github-actions-secret/data/secret K8S_CONFIG | K8S_CONFIG ;  
            github-actions-secret/data/secret DOCKER_CONFIG | DOCKER_CONFIG ;

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: eu-west-1

      - name: Configure K8S credentials
        run: |
          mkdir -p /home/runner/.kube
          echo $K8S_CONFIG | base64 -d > /home/runner/.kube/config
          
      - name: Download frontend build
        run: gh release download ${{ github.event.inputs.image_tag }} -p "frontend-build.zip"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Unzip frontend
        run: unzip frontend-build.zip -d frontend-dist

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: infra/prod

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        working-directory: infra/prod

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: infra/prod

      - name: Terraform Plan
        id: plan
        run: terraform plan -var image_tag=${{ github.event.inputs.image_tag }} -var docker_config=$DOCKER_CONFIG
        working-directory: infra/prod

      - name: Terraform Apply
        id: apply
        run: terraform apply -var image_tag=${{ github.event.inputs.image_tag }} -var docker_config=$DOCKER_CONFIG -auto-approve
        working-directory: infra/prod
