name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  JAVA_VERSION: '25'
  REGISTRY: ghcr.io
  IMAGE_NAME: nicholasm95/meyers-ai

jobs:
  release:
    runs-on: ubuntu-24.04

    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'liberica'
          cache: 'maven'

      - name: Setup Node.js environment
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 24

      - name: Install Semantic Release and plugins
        run: |
          npm install semantic-release @semantic-release/exec @semantic-release/changelog @semantic-release/github

      - name: Log in to the Container registry
        uses: docker/login-action@0567fa5ae8c9a197cb207537dc5cbb43ca3d803f
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate next version
        run: |
          npx semantic-release --dry-run --no-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATE_VERSION_IN_POM: true
        working-directory: ./backend

      - name: Get image tag
        id: tag
        run: echo "IMAGE_TAG=$(cat .image_tag)" >> $GITHUB_OUTPUT
        working-directory: ./backend

      - name: Debug - check file
        run: |
          echo "Does file exist?"
          ls -la .image_tag || echo "FILE NOT FOUND"
          
          echo "File content:"
          cat .image_tag || echo "CANNOT READ"
          
          echo "Content with quotes (check for whitespace/newlines):"
          cat .image_tag | od -c
        working-directory: ./backend


      - name: Get image tag
        id: tag
        run: |
          TAG=$(cat .image_tag | tr -d '\n\r ')
          echo "Cleaned tag: '$TAG'"
          echo "IMAAGE_TAG=$TAG" >> $GITHUB_OUTPUT
        working-directory: ./backend


      - name: Build Project
        run: |
          rm -rf dist
          npm install
          npm run build
        working-directory: ./frontend

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: frontend/dist/**
          tag_name: ${{ steps.tag.outputs.IMAGE_TAG }}

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: frontend/dist/**
          tag_name: $(cat .image_tag)

      - name: Run tests
        run: ./mvnw test
        working-directory: ./backend

      - name: Run install
        run: ./mvnw install -DskipTests
        working-directory: ./backend

      - name: Create Docker image
        run: ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$(cat .image_tag) -pl application -DskipTests
        working-directory: ./backend

      - name: Docker push
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$(cat .image_tag)
        working-directory: ./backend

      - name: Create Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./backend


      - name: Move Changelog
        run: |
          mv backend/CHANGELOG.md CHANGELOG.md

      - name: Update backend CHANGELOG.md
        if: github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "docs(CHANGELOG): Update CHANGELOG.md"
          git push origin main

      - name: Update develop branch
        if: github.ref == 'refs/heads/main'
        run: |
          git fetch origin
          git checkout develop
          git merge --ff-only origin/main
          git push origin develop
